name: "📝 DevOps Project Proposal"
description: "Suggest a new project or resource for HelpOps-Hub"
title: "Project Proposal: "
labels: [project, enhancement]
body:
  - type: textarea
    attributes:
      label: "Overview"
      description: "What is the goal of the project? And which type of technology you are using?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Key Features"
      description: "List the key features and functionalities that this project will include."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Additional Information"
      description: "Any extra details or context."
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: 'I have checked the existing issues'
          required: true

        - label: 'I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)'
          required: true

        - label: 'I am willing to work on this issue (optional)'
          required: false
